name: tests

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: Testing

    # 1) Define the Postgres service with the correct POSTGRES_* vars
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: laravel
          POSTGRES_USER: sail
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd "pg_isready -U sail"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # 2) Tell Laravel to use pgsql + point it at the service above
    env:
      DB_CONNECTION: pgsql
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: sail
      DB_PASSWORD: password

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Add Flux Credentials Loaded From ENV
        run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

      - name: Install PHP Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate --ansi

      - name: Wait for Postgres to be Ready
        # pg_isready is available in the container; if not, install postgresql-client first.
        run: |
          until pg_isready -h 127.0.0.1 -p 5432 -U sail; do
            echo "Waiting for Postgres…"
            sleep 1
          done

      - name: Build Assets
        run: npm run build

      - name: Run Migrations & Seed (optional)
        run: |
          php artisan migrate --no-interaction --force
          # php artisan db:seed --class=YourSeeder

      - name: Run Tests
        run: ./vendor/bin/pest
